# Generated by Django 4.1.3 on 2022-11-29 20:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dono_loja",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("dono_da_loja", models.CharField(max_length=20)),
                ("nome_da_loja", models.CharField(max_length=20)),
            ],
        ),
    ]
