# Generated by Django 4.1.3 on 2022-11-29 20:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("donos_loja", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cnab",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("tipo", models.IntegerField()),
                ("data", models.DateField()),
                ("valor", models.FloatField()),
                ("cartao", models.CharField(max_length=12)),
                ("cpf", models.CharField(max_length=11)),
                ("hora", models.TimeField()),
                (
                    "dono",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cnab",
                        to="donos_loja.dono_loja",
                    ),
                ),
            ],
        ),
    ]
